/** Post's List */
export const POST_FILTER_UPDATE = 'POST_FILTER_UPDATE';

export const POST_LIST_FETCH_START = 'POSTS_FETCH_START';
export const POST_LIST_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POST_LIST_FETCH_FAIL = 'POSTS_FETCH_FAIL';

/** Post details */
export const POST_DETAILS_FETCH_START = 'POST_DETAILS_FETCH_START';
export const POST_DETAILS_FETCH_SUCCESS = 'POST_DETAILS_FETCH_SUCCESS';
export const POST_DETAILS_FETCH_FAIL = 'POST_DETAILS_FETCH_FAIL';

/** Comments */
export const POST_COMMENT_ADD_START = 'POST_COMMENT_ADD_START';
export const POST_COMMENT_ADD_SUCCESS = 'POST_COMMENT_ADD_SUCCESS';
export const POST_COMMENT_ADD_FAIL  = 'POST_COMMENT_ADD_FAIL';

export const POST_COMMENT_DELETE_START = 'POST_COMMENT_DELETE_START';
export const POST_COMMENT_DELETE_SUCCESS = 'POST_COMMENT_DELETE_SUCCESS';
export const POST_COMMENT_DELETE_FAIL  = 'POST_COMMENT_DELETE_FAIL';